// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]
#![allow(unused_mut)]

use wasmlib::*;

pub struct scauriEvents {
}

impl scauriEvents {

	pub fn payout(&self) {
		let mut evt = EventEncoder::new("scauri.payout");
		evt.emit();
	}
}
