// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]

use wasmlib::*;
use crate::*;

#[derive(Clone)]
pub struct ArrayOfImmutableComposition {
	pub(crate) proxy: Proxy,
}

impl ArrayOfImmutableComposition {
    pub fn length(&self) -> u32 {
        self.proxy.length()
    }


	pub fn get_composition(&self, index: u32) -> ImmutableComposition {
		ImmutableComposition { proxy: self.proxy.index(index) }
	}
}

pub type ImmutableCompositions = ArrayOfImmutableComposition;

#[derive(Clone)]
pub struct ArrayOfMutableComposition {
	pub(crate) proxy: Proxy,
}

impl ArrayOfMutableComposition {

	pub fn append_composition(&self) -> MutableComposition {
		MutableComposition { proxy: self.proxy.append() }
	}
	pub fn clear(&self) {
        self.proxy.clear_array();
    }

    pub fn length(&self) -> u32 {
        self.proxy.length()
    }


	pub fn get_composition(&self, index: u32) -> MutableComposition {
		MutableComposition { proxy: self.proxy.index(index) }
	}
}

pub type MutableCompositions = ArrayOfMutableComposition;

#[derive(Clone)]
pub struct ArrayOfImmutableFracComposition {
	pub(crate) proxy: Proxy,
}

impl ArrayOfImmutableFracComposition {
    pub fn length(&self) -> u32 {
        self.proxy.length()
    }


	pub fn get_frac_composition(&self, index: u32) -> ImmutableFracComposition {
		ImmutableFracComposition { proxy: self.proxy.index(index) }
	}
}

pub type ImmutableFracCompositions = ArrayOfImmutableFracComposition;

#[derive(Clone)]
pub struct ArrayOfMutableFracComposition {
	pub(crate) proxy: Proxy,
}

impl ArrayOfMutableFracComposition {

	pub fn append_frac_composition(&self) -> MutableFracComposition {
		MutableFracComposition { proxy: self.proxy.append() }
	}
	pub fn clear(&self) {
        self.proxy.clear_array();
    }

    pub fn length(&self) -> u32 {
        self.proxy.length()
    }


	pub fn get_frac_composition(&self, index: u32) -> MutableFracComposition {
		MutableFracComposition { proxy: self.proxy.index(index) }
	}
}

pub type MutableFracCompositions = ArrayOfMutableFracComposition;

#[derive(Clone)]
pub struct ArrayOfImmutableRecyComposition {
	pub(crate) proxy: Proxy,
}

impl ArrayOfImmutableRecyComposition {
    pub fn length(&self) -> u32 {
        self.proxy.length()
    }


	pub fn get_recy_composition(&self, index: u32) -> ImmutableRecyComposition {
		ImmutableRecyComposition { proxy: self.proxy.index(index) }
	}
}

pub type ImmutableRecyCompositions = ArrayOfImmutableRecyComposition;

#[derive(Clone)]
pub struct ArrayOfMutableRecyComposition {
	pub(crate) proxy: Proxy,
}

impl ArrayOfMutableRecyComposition {

	pub fn append_recy_composition(&self) -> MutableRecyComposition {
		MutableRecyComposition { proxy: self.proxy.append() }
	}
	pub fn clear(&self) {
        self.proxy.clear_array();
    }

    pub fn length(&self) -> u32 {
        self.proxy.length()
    }


	pub fn get_recy_composition(&self, index: u32) -> MutableRecyComposition {
		MutableRecyComposition { proxy: self.proxy.index(index) }
	}
}

pub type MutableRecyCompositions = ArrayOfMutableRecyComposition;
