// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package circularity_artifact

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"

const (
	ScName        = "circularity_artifact"
	ScDescription = "circularity_artifact description"
	HScName       = wasmtypes.ScHname(0x225ea5e1)
)

const (
	ParamChargeWeight    = "chargeWeight"
	ParamCompositions    = "compositions"
	ParamDonationAddress = "donationAddress"
	ParamExpiryDate      = "expiryDate"
	ParamFracID          = "fracID"
	ParamId              = "id"
	ParamName            = "name"
	ParamOwner           = "owner"
	ParamPackageWeight   = "packageWeight"
	ParamPackagesNumber  = "packagesNumber"
	ParamPpID            = "ppID"
	ParamProdID          = "prodID"
	ParamProdPass        = "prodPass"
	ParamPurpose         = "purpose"
	ParamRecyID          = "recyID"
	ParamRecyclerID      = "recyclerID"
	ParamSorterID        = "sorterID"
)

const (
	ResultCompositions    = "compositions"
	ResultDonationAddress = "donationAddress"
	ResultFracComposition = "fracComposition"
	ResultFracID          = "fracID"
	ResultFraction        = "fraction"
	ResultId              = "id"
	ResultOwner           = "owner"
	ResultPp              = "pp"
	ResultPpname          = "ppname"
	ResultPpresult        = "ppresult"
	ResultRecyComposition = "recyComposition"
	ResultRecyID          = "recyID"
	ResultRecyclate       = "recyclate"
	ResultTokenPerPackage = "tokenPerPackage"
	ResultTokenRequired   = "tokenRequired"
)

const (
	StateCompositions      = "compositions"
	StateDonationAddress   = "donationAddress"
	StateFracCompositions  = "fracCompositions"
	StateFractions         = "fractions"
	StateOwner             = "owner"
	StatePricePerMg        = "pricePerMg"
	StateProducersBalances = "producersBalances"
	StateProductpasses     = "productpasses"
	StateRecyCompositions  = "recyCompositions"
	StateRecyclates        = "recyclates"
	StateRecyclers         = "recyclers"
	StateRecyclersBalances = "recyclersBalances"
	StateShareRecycler     = "shareRecycler"
	StateSorters           = "sorters"
	StateTokenToDonate     = "tokenToDonate"
)

const (
	FuncAddPPToFraction          = "addPPToFraction"
	FuncAddRecycler              = "addRecycler"
	FuncAddSorter                = "addSorter"
	FuncCreateFraction           = "createFraction"
	FuncCreatePP                 = "createPP"
	FuncCreateRecyclate          = "createRecyclate"
	FuncDeletePP                 = "deletePP"
	FuncInit                     = "init"
	FuncPayoutDonation           = "payoutDonation"
	FuncPayoutProducer           = "payoutProducer"
	FuncSetDonationAddress       = "setDonationAddress"
	FuncSetOwner                 = "setOwner"
	ViewGetAmountOfRequiredFunds = "getAmountOfRequiredFunds"
	ViewGetDonationAddress       = "getDonationAddress"
	ViewGetFraction              = "getFraction"
	ViewGetMaterials             = "getMaterials"
	ViewGetOwner                 = "getOwner"
	ViewGetPP                    = "getPP"
	ViewGetRecyclate             = "getRecyclate"
	ViewGetTokenPerPackage       = "getTokenPerPackage"
)

const (
	HFuncAddPPToFraction          = wasmtypes.ScHname(0x50ac50a7)
	HFuncAddRecycler              = wasmtypes.ScHname(0x25ae8407)
	HFuncAddSorter                = wasmtypes.ScHname(0x735539b5)
	HFuncCreateFraction           = wasmtypes.ScHname(0x59842fc3)
	HFuncCreatePP                 = wasmtypes.ScHname(0x673fc3d7)
	HFuncCreateRecyclate          = wasmtypes.ScHname(0x5066d840)
	HFuncDeletePP                 = wasmtypes.ScHname(0x56dedc36)
	HFuncInit                     = wasmtypes.ScHname(0x1f44d644)
	HFuncPayoutDonation           = wasmtypes.ScHname(0x4cf2009a)
	HFuncPayoutProducer           = wasmtypes.ScHname(0x3a56494b)
	HFuncSetDonationAddress       = wasmtypes.ScHname(0x5b375a7d)
	HFuncSetOwner                 = wasmtypes.ScHname(0x2a15fe7b)
	HViewGetAmountOfRequiredFunds = wasmtypes.ScHname(0xbcbaf2d6)
	HViewGetDonationAddress       = wasmtypes.ScHname(0x1314f3a7)
	HViewGetFraction              = wasmtypes.ScHname(0xe1c332fa)
	HViewGetMaterials             = wasmtypes.ScHname(0x1dca8ddb)
	HViewGetOwner                 = wasmtypes.ScHname(0x137107a6)
	HViewGetPP                    = wasmtypes.ScHname(0xbf711e08)
	HViewGetRecyclate             = wasmtypes.ScHname(0x4e87f53b)
	HViewGetTokenPerPackage       = wasmtypes.ScHname(0x522a14c0)
)
