// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package circularity_artifact

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"

type MapHashToImmutableCompositions struct {
	proxy wasmtypes.Proxy
}

func (m MapHashToImmutableCompositions) GetCompositions(key wasmtypes.ScHash) ImmutableCompositions {
	return ImmutableCompositions{proxy: m.proxy.Key(wasmtypes.HashToBytes(key))}
}

type MapHashToImmutableFracCompositions struct {
	proxy wasmtypes.Proxy
}

func (m MapHashToImmutableFracCompositions) GetFracCompositions(key wasmtypes.ScHash) ImmutableFracCompositions {
	return ImmutableFracCompositions{proxy: m.proxy.Key(wasmtypes.HashToBytes(key))}
}

type MapHashToImmutableFraction struct {
	proxy wasmtypes.Proxy
}

func (m MapHashToImmutableFraction) GetFraction(key wasmtypes.ScHash) ImmutableFraction {
	return ImmutableFraction{proxy: m.proxy.Key(wasmtypes.HashToBytes(key))}
}

type MapAgentIDToImmutableUint64 struct {
	proxy wasmtypes.Proxy
}

func (m MapAgentIDToImmutableUint64) GetUint64(key wasmtypes.ScAgentID) wasmtypes.ScImmutableUint64 {
	return wasmtypes.NewScImmutableUint64(m.proxy.Key(wasmtypes.AgentIDToBytes(key)))
}

type MapHashToImmutableProductPass struct {
	proxy wasmtypes.Proxy
}

func (m MapHashToImmutableProductPass) GetProductPass(key wasmtypes.ScHash) ImmutableProductPass {
	return ImmutableProductPass{proxy: m.proxy.Key(wasmtypes.HashToBytes(key))}
}

type MapHashToImmutableRecyCompositions struct {
	proxy wasmtypes.Proxy
}

func (m MapHashToImmutableRecyCompositions) GetRecyCompositions(key wasmtypes.ScHash) ImmutableRecyCompositions {
	return ImmutableRecyCompositions{proxy: m.proxy.Key(wasmtypes.HashToBytes(key))}
}

type MapHashToImmutableRecyclate struct {
	proxy wasmtypes.Proxy
}

func (m MapHashToImmutableRecyclate) GetRecyclate(key wasmtypes.ScHash) ImmutableRecyclate {
	return ImmutableRecyclate{proxy: m.proxy.Key(wasmtypes.HashToBytes(key))}
}

type ArrayOfImmutableAgentID struct {
	proxy wasmtypes.Proxy
}

func (a ArrayOfImmutableAgentID) Length() uint32 {
	return a.proxy.Length()
}

func (a ArrayOfImmutableAgentID) GetAgentID(index uint32) wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(a.proxy.Index(index))
}

type Immutablecircularity_artifactState struct {
	proxy wasmtypes.Proxy
}

func (s Immutablecircularity_artifactState) Compositions() MapHashToImmutableCompositions {
	return MapHashToImmutableCompositions{proxy: s.proxy.Root(StateCompositions)}
}

func (s Immutablecircularity_artifactState) DonationAddress() wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(s.proxy.Root(StateDonationAddress))
}

func (s Immutablecircularity_artifactState) FracCompositions() MapHashToImmutableFracCompositions {
	return MapHashToImmutableFracCompositions{proxy: s.proxy.Root(StateFracCompositions)}
}

func (s Immutablecircularity_artifactState) Fractions() MapHashToImmutableFraction {
	return MapHashToImmutableFraction{proxy: s.proxy.Root(StateFractions)}
}

func (s Immutablecircularity_artifactState) Owner() wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(s.proxy.Root(StateOwner))
}

func (s Immutablecircularity_artifactState) PricePerMg() wasmtypes.ScImmutableUint64 {
	return wasmtypes.NewScImmutableUint64(s.proxy.Root(StatePricePerMg))
}

func (s Immutablecircularity_artifactState) ProducersBalances() MapAgentIDToImmutableUint64 {
	return MapAgentIDToImmutableUint64{proxy: s.proxy.Root(StateProducersBalances)}
}

func (s Immutablecircularity_artifactState) Productpasses() MapHashToImmutableProductPass {
	return MapHashToImmutableProductPass{proxy: s.proxy.Root(StateProductpasses)}
}

func (s Immutablecircularity_artifactState) RecyCompositions() MapHashToImmutableRecyCompositions {
	return MapHashToImmutableRecyCompositions{proxy: s.proxy.Root(StateRecyCompositions)}
}

func (s Immutablecircularity_artifactState) Recyclates() MapHashToImmutableRecyclate {
	return MapHashToImmutableRecyclate{proxy: s.proxy.Root(StateRecyclates)}
}

func (s Immutablecircularity_artifactState) Recyclers() ArrayOfImmutableAgentID {
	return ArrayOfImmutableAgentID{proxy: s.proxy.Root(StateRecyclers)}
}

func (s Immutablecircularity_artifactState) RecyclersBalances() MapAgentIDToImmutableUint64 {
	return MapAgentIDToImmutableUint64{proxy: s.proxy.Root(StateRecyclersBalances)}
}

func (s Immutablecircularity_artifactState) ShareRecycler() wasmtypes.ScImmutableUint8 {
	return wasmtypes.NewScImmutableUint8(s.proxy.Root(StateShareRecycler))
}

func (s Immutablecircularity_artifactState) Sorters() ArrayOfImmutableAgentID {
	return ArrayOfImmutableAgentID{proxy: s.proxy.Root(StateSorters)}
}

func (s Immutablecircularity_artifactState) TokenToDonate() wasmtypes.ScImmutableUint64 {
	return wasmtypes.NewScImmutableUint64(s.proxy.Root(StateTokenToDonate))
}

type MapHashToMutableCompositions struct {
	proxy wasmtypes.Proxy
}

func (m MapHashToMutableCompositions) Clear() {
	m.proxy.ClearMap()
}

func (m MapHashToMutableCompositions) GetCompositions(key wasmtypes.ScHash) MutableCompositions {
	return MutableCompositions{proxy: m.proxy.Key(wasmtypes.HashToBytes(key))}
}

type MapHashToMutableFracCompositions struct {
	proxy wasmtypes.Proxy
}

func (m MapHashToMutableFracCompositions) Clear() {
	m.proxy.ClearMap()
}

func (m MapHashToMutableFracCompositions) GetFracCompositions(key wasmtypes.ScHash) MutableFracCompositions {
	return MutableFracCompositions{proxy: m.proxy.Key(wasmtypes.HashToBytes(key))}
}

type MapHashToMutableFraction struct {
	proxy wasmtypes.Proxy
}

func (m MapHashToMutableFraction) Clear() {
	m.proxy.ClearMap()
}

func (m MapHashToMutableFraction) GetFraction(key wasmtypes.ScHash) MutableFraction {
	return MutableFraction{proxy: m.proxy.Key(wasmtypes.HashToBytes(key))}
}

type MapAgentIDToMutableUint64 struct {
	proxy wasmtypes.Proxy
}

func (m MapAgentIDToMutableUint64) Clear() {
	m.proxy.ClearMap()
}

func (m MapAgentIDToMutableUint64) GetUint64(key wasmtypes.ScAgentID) wasmtypes.ScMutableUint64 {
	return wasmtypes.NewScMutableUint64(m.proxy.Key(wasmtypes.AgentIDToBytes(key)))
}

type MapHashToMutableProductPass struct {
	proxy wasmtypes.Proxy
}

func (m MapHashToMutableProductPass) Clear() {
	m.proxy.ClearMap()
}

func (m MapHashToMutableProductPass) GetProductPass(key wasmtypes.ScHash) MutableProductPass {
	return MutableProductPass{proxy: m.proxy.Key(wasmtypes.HashToBytes(key))}
}

type MapHashToMutableRecyCompositions struct {
	proxy wasmtypes.Proxy
}

func (m MapHashToMutableRecyCompositions) Clear() {
	m.proxy.ClearMap()
}

func (m MapHashToMutableRecyCompositions) GetRecyCompositions(key wasmtypes.ScHash) MutableRecyCompositions {
	return MutableRecyCompositions{proxy: m.proxy.Key(wasmtypes.HashToBytes(key))}
}

type MapHashToMutableRecyclate struct {
	proxy wasmtypes.Proxy
}

func (m MapHashToMutableRecyclate) Clear() {
	m.proxy.ClearMap()
}

func (m MapHashToMutableRecyclate) GetRecyclate(key wasmtypes.ScHash) MutableRecyclate {
	return MutableRecyclate{proxy: m.proxy.Key(wasmtypes.HashToBytes(key))}
}

type ArrayOfMutableAgentID struct {
	proxy wasmtypes.Proxy
}

func (a ArrayOfMutableAgentID) AppendAgentID() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(a.proxy.Append())
}

func (a ArrayOfMutableAgentID) Clear() {
	a.proxy.ClearArray()
}

func (a ArrayOfMutableAgentID) Length() uint32 {
	return a.proxy.Length()
}

func (a ArrayOfMutableAgentID) GetAgentID(index uint32) wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(a.proxy.Index(index))
}

type Mutablecircularity_artifactState struct {
	proxy wasmtypes.Proxy
}

func (s Mutablecircularity_artifactState) AsImmutable() Immutablecircularity_artifactState {
	return Immutablecircularity_artifactState(s)
}

func (s Mutablecircularity_artifactState) Compositions() MapHashToMutableCompositions {
	return MapHashToMutableCompositions{proxy: s.proxy.Root(StateCompositions)}
}

func (s Mutablecircularity_artifactState) DonationAddress() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(s.proxy.Root(StateDonationAddress))
}

func (s Mutablecircularity_artifactState) FracCompositions() MapHashToMutableFracCompositions {
	return MapHashToMutableFracCompositions{proxy: s.proxy.Root(StateFracCompositions)}
}

func (s Mutablecircularity_artifactState) Fractions() MapHashToMutableFraction {
	return MapHashToMutableFraction{proxy: s.proxy.Root(StateFractions)}
}

func (s Mutablecircularity_artifactState) Owner() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(s.proxy.Root(StateOwner))
}

func (s Mutablecircularity_artifactState) PricePerMg() wasmtypes.ScMutableUint64 {
	return wasmtypes.NewScMutableUint64(s.proxy.Root(StatePricePerMg))
}

func (s Mutablecircularity_artifactState) ProducersBalances() MapAgentIDToMutableUint64 {
	return MapAgentIDToMutableUint64{proxy: s.proxy.Root(StateProducersBalances)}
}

func (s Mutablecircularity_artifactState) Productpasses() MapHashToMutableProductPass {
	return MapHashToMutableProductPass{proxy: s.proxy.Root(StateProductpasses)}
}

func (s Mutablecircularity_artifactState) RecyCompositions() MapHashToMutableRecyCompositions {
	return MapHashToMutableRecyCompositions{proxy: s.proxy.Root(StateRecyCompositions)}
}

func (s Mutablecircularity_artifactState) Recyclates() MapHashToMutableRecyclate {
	return MapHashToMutableRecyclate{proxy: s.proxy.Root(StateRecyclates)}
}

func (s Mutablecircularity_artifactState) Recyclers() ArrayOfMutableAgentID {
	return ArrayOfMutableAgentID{proxy: s.proxy.Root(StateRecyclers)}
}

func (s Mutablecircularity_artifactState) RecyclersBalances() MapAgentIDToMutableUint64 {
	return MapAgentIDToMutableUint64{proxy: s.proxy.Root(StateRecyclersBalances)}
}

func (s Mutablecircularity_artifactState) ShareRecycler() wasmtypes.ScMutableUint8 {
	return wasmtypes.NewScMutableUint8(s.proxy.Root(StateShareRecycler))
}

func (s Mutablecircularity_artifactState) Sorters() ArrayOfMutableAgentID {
	return ArrayOfMutableAgentID{proxy: s.proxy.Root(StateSorters)}
}

func (s Mutablecircularity_artifactState) TokenToDonate() wasmtypes.ScMutableUint64 {
	return wasmtypes.NewScMutableUint64(s.proxy.Root(StateTokenToDonate))
}
